apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-lab16
  labels:
    app: frontend-lab16
spec:
  selector:
    matchLabels:
      app: frontend-lab16
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-lab16
    spec:
      containers:
        - name: frontend-lab16
          image: kongru/frontend-lab16
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
